### ISSUE TITLE
Remove all the build files and add .gitignore

### ISSUE THREAD

**Issue by selvakn** [TWChennai/LocateXBackend#1]
@abdulrahman-tw : All the build output and the intellj files are version controlled. Please remove them and add an .gitignore file.

**Comment by vraravam** [comment]
Or better yet, if there have not been too many commits on top, please use the ```git filter-branch``` command to remove the files from the git history permanently.

**Comment by abdulrahman-tw** [comment]
Done removing .idea and out files
